# Generated by Django 5.2.9 on 2026-01-03 14:22

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_progress_reviewed_at_progress_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='blockchain_block_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='blockchain_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fund',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for fund release', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='actual_lifespan_years',
            field=models.PositiveIntegerField(blank=True, help_text='Actual lifespan (filled when work deteriorates)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='blockchain_contract_address',
            field=models.CharField(blank=True, help_text='Smart contract address on blockchain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for project creation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_size',
            field=models.CharField(choices=[('SMALL', 'Small (< 10 Lakh)'), ('MEDIUM', 'Medium (10 Lakh - 1 Crore)'), ('LARGE', 'Large (> 1 Crore)')], default='SMALL', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='expected_lifespan_years',
            field=models.PositiveIntegerField(default=10, help_text='Expected lifespan of the completed work in years'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_contractor_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Minimum contractor rating required for this project', max_digits=3),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('ABANDONED', 'Abandoned')], default='PLANNING', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_period_years',
            field=models.PositiveIntegerField(default=1, help_text='Warranty period in years'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nepal_nid',
            field=models.CharField(blank=True, help_text='Nepal NID format: District-Ward-Number (e.g., 01-05-12345678)', max_length=20, null=True, validators=[core.models.validate_nepal_nid]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nid_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('total_projects_completed', models.PositiveIntegerField(default=0)),
                ('total_projects_failed', models.PositiveIntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('qualification_test_score', models.PositiveIntegerField(blank=True, help_text='Score from qualification test (0-100)', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('test_passed', models.BooleanField(default=False)),
                ('test_taken_at', models.DateTimeField(blank=True, null=True)),
                ('ai_rating', models.DecimalField(blank=True, decimal_places=2, help_text='AI-generated rating based on historical performance', max_digits=3, null=True)),
                ('ai_rating_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI-calculated risk score for project delays/failures', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verified', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.contractorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.contractorprofile'),
        ),
        migrations.CreateModel(
            name='ContractorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveIntegerField(help_text='Rating from 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_negative', models.BooleanField(default=False)),
                ('evidence_required', models.BooleanField(default=False)),
                ('evidence_provided', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.contractorprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_ratings', to='core.project')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contractor', 'project', 'rated_by')},
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('NATURAL_DISASTER', 'Natural Disaster'), ('CONTRACTOR_FAULT', 'Contractor Fault'), ('DESIGN_FLAW', 'Design Flaw'), ('MATERIAL_DEFECT', 'Material Defect'), ('VANDALISM', 'Vandalism'), ('NORMAL_WEAR', 'Normal Wear and Tear'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('FORGIVEN', 'Forgiven'), ('PENALIZED', 'Penalized'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=15)),
                ('is_forgivable', models.BooleanField(default=False)),
                ('forgiveness_reason', models.TextField(blank=True)),
                ('is_forgiven', models.BooleanField(default=False)),
                ('forgiven_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rating_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Rating points deducted from contractor', max_digits=3, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forgiven_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forgiven_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.project')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default='PHOTO', max_length=10)),
                ('file', models.FileField(upload_to='issue_evidence/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.issuereport')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('TON', 'Ton'), ('UNIT', 'Unit/Piece'), ('LITER', 'Liter'), ('SQFT', 'Square Feet'), ('SQMT', 'Square Meter'), ('CUFT', 'Cubic Feet'), ('CUMT', 'Cubic Meter'), ('BAG', 'Bag'), ('BUNDLE', 'Bundle')], default='UNIT', max_length=10)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_planned_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('total_actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateTimeField()),
                ('payment_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='RatingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default='PHOTO', max_length=10)),
                ('file', models.FileField(upload_to='rating_evidence/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.contractorrating')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.PositiveIntegerField(help_text='Proficiency level from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('years_of_practice', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.contractorprofile')),
            ],
            options={
                'unique_together': {('contractor', 'skill_name')},
            },
        ),
    ]
